// How is JS code executed
// JAVASCRIPT EXECUTION CONTEXT.... HOW JS RUNS OR EXECUTES A FILE YOU CREATED INSIDE VSCODE

// WHEN WE WRITE A CODE , FIRSTLY GLOBAL EXECUTION CONTEXT IS CREATED , AND THEN THIS GLOBAL EC IS STORED OR PUT IN (this) KEYWORD
// GLOBAL EXECUTION CONTEXT and FUNCTION EXECUTION CONTEXT and EVAL EXECUTION CONTEXT

// MEMORY CREATION PHASE: IN THIS PHASE ONLY A LOCATION IS ALLOCATED FOR THE VARIBALES YOU HAVE CREATED
// EXECUTION PHASE: IN THIS PHASE ALL THE ACTIVITIES ARE EXECUTED HERE LIKE ADDITION, SUBTRACTION ETC

let val1 = 10
let val2 = 20
function addNum(num1,num2){
  let total = num1 + num2
  return total
}
let result1 = addNum(val1, val2)
let result2 = addNum(10,3)

// HOW WILL THIS CODE BE EXECUTED
// STEP1: GLOBAL EXECUTION CREATED AND IS PUT IT IN (this) KEYWORD
// STEP2: MEMORY CREATION PHASE
// VAL1 = UNDEFINED
// VAL2 = UNDEFINED
// ADDNUM = FUNCTION DEFINTION WILL BE STORED
// RESULT1 = UNDEFINED
// RESULT2 = UNDEFINED

// STEP3: EXECUTION PHASE
// VAL1 = 10
// VAL2 = 20
// ADDNUM = NEW VARIABLE ENVIORNMENT + EXECUTION THREAD WILL BE CREATED , BCZ OF LINE16(RESULT1)
// RESULT1 = 15 .... ADDED AFTER 43 NUMBER LINE
// RESULT2 = 13 .... ADDED AFTER 53 NUMBER LINE

// NEW EXECUTIIONAL THREAD CREATED SO AGAIN REPEAT THESE 2 STEPS
// MEMORY CREATION PHASE:
// VAL1 = UNDEFINED
// VAL2 = UNDEFINED
// TOTAL = UNDEFINED
// EXECUTION PHASE:
// NUM1 = 10
// NUM2 = 20
// TOTAL = 15
// AFTER THE ACTION IS DONE THE ABOVE ENVIORNEMENT WHICH IS CREATED GETS DELETED

// NOW FOR RESULT2 ... NEW VARIABLE ENVIORNMENT + EXECUTION THREAD WILL BE CREATED 
// MEMORY CREATION PHASE:
// VAL1 = UNDEFINED
// VAL2 = UNDEFINED
// TOTAL = UNDEFINED
// EXECUTION PHASE:
// NUM1 : 10
// NUM2 : 3
// TOTAL: 13
// AFTER THE ACTION IS DONE THE ABOVE ENVIORNEMENT WHICH IS CREATED GETS DELETED

